cabal-version: 3.0
name: keiro-dsl-conformance-service-runtime
version: 0.0.0.0
synopsis: Runtime library for the generated service-package conformance proof
license: BSD-3-Clause
build-type: Simple

library
  hs-source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    Proof.WorkspaceProof.Generated.Conformance
  other-modules:
    Proof.WorkspaceProof.Alpha.BehaviorHoles
    Proof.WorkspaceProof.Alpha.Generated.BehaviorContract
    Proof.WorkspaceProof.Alpha.Generated.Codec
    Proof.WorkspaceProof.Alpha.Generated.Domain
    Proof.WorkspaceProof.Alpha.Generated.EventStream
    Proof.WorkspaceProof.Alpha.Generated.Harness
    Proof.WorkspaceProof.Alpha.Generated.Projection
    Proof.WorkspaceProof.Alpha.Generated.Transducer
    Proof.WorkspaceProof.AlphaView.Generated.ReadModel
    Proof.WorkspaceProof.AlphaView.Generated.ReadModelHarness
    Proof.WorkspaceProof.AlphaView.Generated.ReadModelTable
    Proof.WorkspaceProof.AlphaView.ReadModelHoles
    Proof.WorkspaceProof.Beta.BehaviorHoles
    Proof.WorkspaceProof.Beta.Generated.BehaviorContract
    Proof.WorkspaceProof.Beta.Generated.Codec
    Proof.WorkspaceProof.Beta.Generated.Domain
    Proof.WorkspaceProof.Beta.Generated.EventStream
    Proof.WorkspaceProof.Beta.Generated.Harness
    Proof.WorkspaceProof.Beta.Generated.Projection
    Proof.WorkspaceProof.Beta.Generated.Transducer
    Proof.WorkspaceProof.BetaView.Generated.ReadModel
    Proof.WorkspaceProof.BetaView.Generated.ReadModelHarness
    Proof.WorkspaceProof.BetaView.Generated.ReadModelTable
    Proof.WorkspaceProof.BetaView.ReadModelHoles
    Proof.WorkspaceProof.Generated.BehaviorSourceMap
    Proof.WorkspaceProof.Generated.Nominals
    Proof.WorkspaceProof.Generated.Nominals.Internal
    Proof.WorkspaceProof.Generated.ReplayAudit
    Proof.WorkspaceProof.WorkspaceProofWorkflow.Generated.WorkflowFacts
    Proof.WorkspaceProof.WorkspaceProofWorkflow.Generated.WorkflowRuntime
  build-depends:
      aeson
    , base
    , containers
    , effectful-core
    , hasql-transaction
    , keiki
    , keiro
    , kiroku-store
    , text
  default-language: GHC2024
  default-extensions:
    ImportQualifiedPost
    OverloadedLabels
    OverloadedStrings
