{- | Service workspaces: several complete @.keiro@ member files validated,
scaffolded, and diffed as __one service contract__.

A /workspace manifest/ is a @.keiro-workspace@ file that names the service and
lists its member @.keiro@ files. It is deliberately a file rather than repeated
CLI flags: @keiro-dsl diff --since \<rev\>@ must be able to reconstruct the
member set as it existed at an older git revision from git alone, and the
scaffold record needs one durable identity that outlives member renames.

The manifest is line-oriented in the spirit of the member grammar: @#@ starts a
comment, blank lines are insignificant, and clause keywords drive structure.

@
# The demo-project service workspace.
service demo-project
module Demo.Modules.Project
layout collocated
spec domain/project-artifact.keiro
spec domain/project.keiro
spec domain/shared.keiro
@

Membership is a __set__: 'parseWorkspaceManifest' accepts @spec@ lines in any
order and canonically sorts them (codepoint order on the normalized relative
path), and 'renderWorkspaceManifest' always emits that canonical order. Source
order therefore never changes meaning or generated bytes.

This module owns the workspace file format only; the member @.keiro@ grammar in
"Keiro.Dsl.Parser" is untouched. Note the unrelated "Keiro.Dsl.Manifest", which
is the /scaffold build manifest/ (the record of emitted modules) — every
identifier here carries a @Workspace@ prefix to keep the two apart.
-}
module Keiro.Dsl.Workspace (
    -- * The workspace manifest
    WorkspaceManifest (..),
    WorkspaceMemberRef (..),
    parseWorkspaceManifest,
    renderWorkspaceManifest,

    -- * Input dispatch
    workspaceExtension,
    isWorkspacePath,

    -- * Member paths
    normalizeMemberPath,
) where

import Data.Char (isAscii, isDigit, isLetter, toLower)
import Data.List (sortOn)
import Data.List.NonEmpty (NonEmpty (..))
import Data.List.NonEmpty qualified as NE
import Data.Text (Text)
import Data.Text qualified as T
import Data.Void (Void)
import Keiro.Dsl.Grammar (Loc (..), Placement (..))
import Keiro.Dsl.Parser (ParseError)
import Text.Megaparsec hiding (ParseError)
import Text.Megaparsec.Char (char, space1)
import Text.Megaparsec.Char.Lexer qualified as L

{- | A parsed workspace manifest. Members are held in canonical order
(codepoint-sorted normalized paths), so two manifests that list the same
members in different source orders are 'Eq'-equal and render to identical
bytes.

Unlike 'Keiro.Dsl.Grammar.Spec', which records no location for its
@context@\/@module@\/@layout@ clauses, this type keeps a 'Loc' per clause: the
workspace composer needs to cite a manifest clause line when a member
contradicts it.
-}
data WorkspaceManifest = WorkspaceManifest
    { wmfService :: !Text
    -- ^ The stable workspace identity, e.g. @demo-project@.
    , wmfServiceLoc :: !Loc
    , wmfModuleRoot :: !(Maybe Text)
    -- ^ The optional @module@ clause: the workspace's module-root authority.
    , wmfModuleRootLoc :: !Loc
    -- ^ Meaningful only when 'wmfModuleRoot' is 'Just'.
    , wmfLayout :: !(Maybe Placement)
    -- ^ The optional @layout@ clause: the workspace's placement authority.
    , wmfLayoutLoc :: !Loc
    -- ^ Meaningful only when 'wmfLayout' is 'Just'.
    , wmfMembers :: !(NonEmpty WorkspaceMemberRef)
    -- ^ At least one member, in canonical order.
    }
    deriving stock (Eq, Show)

-- | One @spec \<path\>@ line: the normalized manifest-relative member path.
data WorkspaceMemberRef = WorkspaceMemberRef
    { wmrPath :: !FilePath
    -- ^ Normalized: forward slashes, no @./@ segments, relative, ends in @.keiro@.
    , wmrLoc :: !Loc
    }
    deriving stock (Eq, Show)

-- | The file extension that marks a workspace manifest.
workspaceExtension :: String
workspaceExtension = ".keiro-workspace"

{- | Does this @FILE@ argument name a workspace manifest? The test is on the
extension, case-insensitively, and never on the file's content: a file's role
must not depend on which parser happens to succeed, and a corrupted manifest
must produce a manifest parse error rather than a confusing @.keiro@ one.
-}
isWorkspacePath :: FilePath -> Bool
isWorkspacePath path = map toLower workspaceExtension `isSuffixOfString` map toLower path
  where
    isSuffixOfString needle haystack = length haystack > length needle && drop (length haystack - length needle) haystack == needle

--------------------------------------------------------------------------------
-- Member path normalization
--------------------------------------------------------------------------------

{- | Normalize and validate a @spec@ path token. Member paths must be relative,
use forward slashes, end in @.keiro@, and stay inside the manifest's directory
tree; @.\/@ segments are normalized away. A manifest may not list another
manifest (a @.keiro-workspace@ path fails the @.keiro@ suffix rule).

The restrictions exist so a workspace can be reconstructed at an arbitrary git
revision with @git show \<rev\>:\<repo-relative-path\>@: a path that escapes the
repository cannot be reconstructed at all. Every rule can be relaxed additively
later; none can be tightened without breaking users.

Returns 'Left' with a human-readable reason, or 'Right' the normalized path.
-}
normalizeMemberPath :: Text -> Either Text FilePath
normalizeMemberPath raw
    | T.null raw = Left "member path is empty"
    | T.isPrefixOf "/" raw = Left ("member path must be relative, not absolute: '" <> raw <> "'")
    | ".." `elem` segments = Left ("member path must not contain '..' segments: '" <> raw <> "'")
    | null kept = Left ("member path is empty after normalization: '" <> raw <> "'")
    | not (T.isSuffixOf ".keiro" normalized) =
        Left ("member path must name a .keiro spec: '" <> raw <> "'")
    | normalized == ".keiro" = Left ("member path must name a .keiro spec: '" <> raw <> "'")
    | otherwise = Right (T.unpack normalized)
  where
    segments = T.splitOn "/" raw
    kept = [s | s <- segments, not (T.null s), s /= "."]
    normalized = T.intercalate "/" kept

--------------------------------------------------------------------------------
-- Parser
--------------------------------------------------------------------------------

type WP = Parsec Void Text

{- | Parse a workspace manifest. The 'FilePath' is used only as the source name
in diagnostics (megaparsec's line reporting); it need not exist on disk.

Duplicate clauses, a missing or misplaced @service@ clause, an empty member
list, an invalid member path, and duplicate members (including two paths equal
under Unicode case folding — macOS's default filesystem is case-insensitive, so
two such paths can silently be one file) are all rejected here, at the manifest
boundary, with the manifest path and line.
-}
parseWorkspaceManifest :: FilePath -> Text -> Either ParseError WorkspaceManifest
parseWorkspaceManifest src input =
    case runParser (sc *> pManifest <* eof) src input of
        Left bundle -> Left (T.pack (errorBundlePretty bundle))
        Right manifest -> Right manifest

-- | One source clause, tagged with the offset used to position its diagnostics.
data Clause
    = ClService !Int !Loc !Text
    | ClModule !Int !Loc !Text
    | ClLayout !Int !Loc !Placement
    | ClSpec !Int !Loc !Text

clauseOffset :: Clause -> Int
clauseOffset (ClService o _ _) = o
clauseOffset (ClModule o _ _) = o
clauseOffset (ClLayout o _ _) = o
clauseOffset (ClSpec o _ _) = o

-- | Space consumer: spaces, newlines, and @#@ line comments are all whitespace.
sc :: WP ()
sc = L.space space1 (L.skipLineComment "#") empty

lexeme :: WP a -> WP a
lexeme = L.lexeme sc

-- | A literal keyword not followed by an identifier character.
keyword :: Text -> WP ()
keyword word = lexeme (try (chunk word *> notFollowedBy (satisfy pathChar)))

getLoc :: WP Loc
getLoc = (Loc . unPos . sourceLine) <$> getSourcePos

pManifest :: WP WorkspaceManifest
pManifest = do
    startOffset <- getOffset
    clauses <- many pClause
    buildManifest startOffset clauses

pClause :: WP Clause
pClause =
    choice
        [ mk ClService "service" pServiceName
        , mk ClModule "module" pModulePrefix
        , mk ClLayout "layout" pPlacement
        , mk ClSpec "spec" pPathToken
        ]
  where
    mk construct word value = try $ do
        offset <- getOffset
        loc <- getLoc
        keyword word
        construct offset loc <$> value

{- | The workspace identity uses the member grammar's wire-word spelling: an
ASCII letter or digit, then letters, digits, @_@, and @-@ (e.g. @mori-project@).
-}
pServiceName :: WP Text
pServiceName = lexeme $ do
    c <- satisfy asciiAlphaNum <?> "workspace service name"
    cs <- many (satisfy (\x -> asciiAlphaNum x || x == '_' || x == '-'))
    pure (T.pack (c : cs))

{- | A dotted module prefix: one-or-more PascalCase segments joined by dots,
matching the member grammar's @module@ clause (e.g. @Demo.Modules.Project@).
-}
pModulePrefix :: WP Text
pModulePrefix = lexeme $ do
    seg0 <- pSeg
    segs <- many (char '.' *> pSeg)
    pure (T.intercalate "." (seg0 : segs))
  where
    pSeg = do
        c <- satisfy (\x -> x >= 'A' && x <= 'Z') <?> "PascalCase module segment"
        cs <- many (satisfy (\x -> asciiAlphaNum x || x == '_'))
        pure (T.pack (c : cs))

pPlacement :: WP Placement
pPlacement =
    choice
        [ GeneratedPrefix <$ keyword "prefixed"
        , CollocatedLeaf <$ keyword "collocated"
        ]
        <?> "'prefixed' or 'collocated'"

-- | A relative path token: no spaces, no drive letters, no quoting.
pPathToken :: WP Text
pPathToken = lexeme (T.pack <$> some (satisfy pathChar)) <?> "relative .keiro member path"

pathChar :: Char -> Bool
pathChar c = asciiAlphaNum c || c == '.' || c == '_' || c == '-' || c == '/'

asciiAlphaNum :: Char -> Bool
asciiAlphaNum c = isAscii c && (isLetter c || isDigit c)

{- | Fold the parsed clauses into a manifest, rejecting every structural error
at the offending clause's own source position.
-}
buildManifest :: Int -> [Clause] -> WP WorkspaceManifest
buildManifest startOffset clauses = do
    case clauses of
        [] -> failAt startOffset "workspace manifest must begin with a 'service <name>' clause"
        first : _ -> case first of
            ClService{} -> pure ()
            other -> failAt (clauseOffset other) "the first clause of a workspace manifest must be 'service <name>'"
    (service, serviceLoc) <- case [(name, loc) | ClService _ loc name <- clauses] of
        [one] -> pure one
        _ -> failAt (secondOffset [c | c@ClService{} <- clauses]) "duplicate 'service' clause: a workspace has exactly one identity"
    (moduleRoot, moduleLoc) <- case [(root, loc) | ClModule _ loc root <- clauses] of
        [] -> pure (Nothing, Loc 0)
        [(root, loc)] -> pure (Just root, loc)
        _ -> failAt (secondOffset [c | c@ClModule{} <- clauses]) "duplicate 'module' clause"
    (layout, layoutLoc) <- case [(placement, loc) | ClLayout _ loc placement <- clauses] of
        [] -> pure (Nothing, Loc 0)
        [(placement, loc)] -> pure (Just placement, loc)
        _ -> failAt (secondOffset [c | c@ClLayout{} <- clauses]) "duplicate 'layout' clause"
    let specClauses = [(offset, loc, raw) | ClSpec offset loc raw <- clauses]
    normalized <- traverse normalizeOne specClauses
    case normalized of
        [] -> failAt startOffset "workspace manifest must list at least one 'spec <path>.keiro' member"
        _ -> pure ()
    rejectDuplicates normalized
    let sorted = sortOn (T.pack . snd3) normalized
    pure
        WorkspaceManifest
            { wmfService = service
            , wmfServiceLoc = serviceLoc
            , wmfModuleRoot = moduleRoot
            , wmfModuleRootLoc = moduleLoc
            , wmfLayout = layout
            , wmfLayoutLoc = layoutLoc
            , wmfMembers = NE.fromList [WorkspaceMemberRef path loc | (_, path, loc) <- sorted]
            }
  where
    snd3 (_, path, _) = path
    normalizeOne (offset, loc, raw) = case normalizeMemberPath raw of
        Left reason -> failAt offset (T.unpack reason)
        Right path -> pure (offset, path, loc)
    secondOffset cs = case cs of
        _ : second : _ -> clauseOffset second
        _ -> startOffset

{- | Refuse a member listed twice, and a member listed under two spellings that
case-fold to the same path. Detecting a source file assigned to /two different/
workspaces is deliberately out of scope here: one invocation sees one manifest,
and repository-wide manifest discovery is exactly the dynamic discovery this
design excludes.
-}
rejectDuplicates :: [(Int, FilePath, Loc)] -> WP ()
rejectDuplicates entries = go [] entries
  where
    go _ [] = pure ()
    go seen ((offset, path, _) : rest)
        | path `elem` map fst seen =
            failAt offset ("duplicate workspace member '" <> path <> "': membership is a set")
        | Just earlier <- lookup (T.toCaseFold (T.pack path)) (map swap seen) =
            failAt
                offset
                ( "workspace members '"
                    <> earlier
                    <> "' and '"
                    <> path
                    <> "' differ only by case; on a case-insensitive filesystem they are one file"
                )
        | otherwise = go ((path, T.toCaseFold (T.pack path)) : seen) rest
    swap (path, folded) = (folded, path)

-- | Fail with a plain message positioned at a specific source offset.
failAt :: Int -> String -> WP a
failAt offset message = setOffset offset >> fail message

--------------------------------------------------------------------------------
-- Renderer
--------------------------------------------------------------------------------

{- | Render a manifest in canonical form: @service@, then the optional @module@
and @layout@ clauses, then the members in codepoint order, one per line, with
no trailing newline (comments are not preserved, exactly like the member
pretty-printer). @parse . render@ is the identity on the AST and
@render . parse . render@ is the identity on bytes.
-}
renderWorkspaceManifest :: WorkspaceManifest -> Text
renderWorkspaceManifest manifest =
    T.intercalate "\n" $
        ["service " <> wmfService manifest]
            ++ maybe [] (\root -> ["module " <> root]) (wmfModuleRoot manifest)
            ++ maybe [] (\placement -> ["layout " <> renderPlacement placement]) (wmfLayout manifest)
            ++ [ "spec " <> T.pack (wmrPath member)
               | member <- sortOn (T.pack . wmrPath) (NE.toList (wmfMembers manifest))
               ]

renderPlacement :: Placement -> Text
renderPlacement GeneratedPrefix = "prefixed"
renderPlacement CollocatedLeaf = "collocated"
